### ISSUE TITLE
运行后出现以下错误

### ISSUE THREAD

**Issue by glenty3** [zhcong/homeassistant-atHome#1]
小白求助 
首先十分感谢大大的代码分享
运行后出现以下错误，大大有空时麻烦帮忙看一下呗 谢谢谢谢~

C:\Users\admin\AppData\Local\Programs\Python\Python39\python.exe C:/Users/admin/PycharmProjects/火锅视频/dist/MQTT.py
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\火锅视频\dist\MQTT.py", line 88, in <module>
    run()
  File "C:\Users\admin\PycharmProjects\火锅视频\dist\MQTT.py", line 70, in run
    client = connectMqtt()
  File "C:\Users\admin\PycharmProjects\火锅视频\dist\MQTT.py", line 43, in connectMqtt
    client = mqtt_client.Client(client_id)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\paho\mqtt\client.py", line 766, in __init__
    raise ValueError(
ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see migrations.md for details

Process finished with exit code 1

**Comment by zhcong** [comment]
看上去像是mqtt client的版本问题，稍后给出可以使用的依赖的版本

**Comment by zhcong** [comment]
arprequest 0.3
paho-mqtt  1.6.1
